name: Reusable Sample Workflow

on:
  workflow_call:
    inputs:
      arg1:
        required: true
        type: string
      arg2:
        required: true
        type: string
      arg3:
        required: true
        type: string

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print arguments
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Argument 1: " + "${{ inputs.arg1 }}");
            console.log("Argument 2: " + "${{ inputs.arg2 }}");
            console.log("Argument 3: " + "${{ inputs.arg3 }}");
