name: Sample Workflow

on:
  push:
    branches: [master]

jobs:
  call_reusable1:
    uses: ./.github/workflows/reusable_sample.yml
    with:
      arg1: "Hello World!"
      arg2: |
        Hello World!
      arg3: >-
        Hello World!
